import { fetchApi } from './client';

// ─── Shared ───────────────────────────────────────────────────────────────────

export interface ChargeProduct {
  name: string;
  price: string;       // API expects string e.g. "10.00"
  quantity: string;    // API expects string e.g. "1"
  description?: string;
}

// ─── One-Time Charges ─────────────────────────────────────────────────────────

export interface CreateChargePayload {
  charge: {
    payer_name?: string;
    payer_email?: string;
    expiration_date?: string; // "DD/MM/YYYY"
    code?: string;
    description?: string;
    products: ChargeProduct[];
  };
}

export interface ApiCharge {
  id: string;
  token: string;
  code: string;
  description: string;
  price: number;
  status: 'NOT_PAID' | 'PAID' | 'EXPIRED' | 'CANCELLED' | string;
  expiration_date: string;
  payer_name?: string;
  payer_email?: string;
  products?: ChargeProduct[];
  created_at?: string;
  updated_at?: string;
  checkout_url?: string;
  invoice_url?: string;
}

export interface ChargesListResponse {
  charges: ApiCharge[];
  meta: { current_page: number; per_page: number; total_count: number };
}

export interface ChargeDetailResponse {
  charge: ApiCharge;
}

export interface ChargesListParams {
  price?: number;
  status?: string;
  payer_name?: string;
  payer_email?: string;
  expiration_date_gt?: string;
  expiration_date_lt?: string;
  page?: number;
  per_page?: number;
}

// ─── Subscription Plans ───────────────────────────────────────────────────────

export interface CreatePlanPayload {
  name: string;
  description?: string;
  code?: string;
  price: string; // "10.00"
  /** Periodicity in months: 1=monthly, 3=quarterly, 6=semiannual, 12=annual */
  periodicity: number;
  public?: boolean;
}

export interface ApiPlan {
  id: string;
  token: string;
  name: string;
  description?: string;
  code?: string;
  price: number;
  periodicity: number;
  public: boolean;
  status: string;
  created_at?: string;
}

export interface PlansListResponse {
  plans: ApiPlan[];
  meta: { current_page: number; per_page: number; total_count: number };
}

export interface PlanDetailResponse {
  plan: ApiPlan;
}

// ─── Subscriptions ────────────────────────────────────────────────────────────

export interface SubscriptionCustomer {
  id?: string;
  name: string;
  email: string;
  document: string;
  phone?: string;
}

export interface CreateSubscriptionPayload {
  subscription: {
    customer: SubscriptionCustomer;
    code?: string;
    plans: { id: string; price?: number }[];
    items?: { description: string; price: number }[];
  };
}

export interface ApiSubscription {
  id: string;
  token: string;
  code?: string;
  status: 'active' | 'cancelled' | 'suspended' | string;
  customer: { id: string; name: string; email: string };
  plan?: ApiPlan;
  plans?: ApiPlan[];
  expiration_day?: number;
  created_at?: string;
  next_billing_date?: string;
}

export interface SubscriptionsListResponse {
  subscriptions: ApiSubscription[];
  meta: { current_page: number; per_page: number; total_count: number };
}

export interface SubscriptionDetailResponse {
  subscription: ApiSubscription;
}

// ─── Invoices (auto-generated by subscriptions) ───────────────────────────────

export interface ApiInvoice {
  id: string;
  token: string;
  status: 'waiting_payment' | 'paid' | 'expired' | string;
  price: number;
  expiration_date?: string;
  starts_at?: string;
  ends_at?: string;
  subscription?: { token: string; code?: string };
  created_at?: string;
}

export interface InvoicesListResponse {
  invoices: ApiInvoice[];
  meta: { current_page: number; per_page: number; total_count: number };
}

// ─── Payment / Checkout ───────────────────────────────────────────────────────

export interface ProcessPaymentPayload {
  token: string;
  payment_method: 'credit_card' | 'pix';
  card_number?: string;
  card_holder_name?: string;
  card_expiration_date?: string;
  card_cvv?: string;
  installments?: number;
  customer_name: string;
  customer_email: string;
  customer_document: string;
  customer_phone: string;
}

export interface ProcessSubscriptionPaymentPayload {
  /** plan token */
  plan_token: string;
  customer: SubscriptionCustomer;
  payment: {
    method: 'credit_card' | 'pix';
    recurrency: true;
    card_number?: string;
    card_holder_name?: string;
    card_expiration_date?: string;
    card_cvv?: string;
    installments?: number;
  };
}

// ─── Unified "charge" shape used in UI ───────────────────────────────────────

export type ChargeType = 'one_time' | 'subscription';

export interface UnifiedCharge {
  type: ChargeType;
  token: string;
  code?: string;
  description: string;
  price: number;
  status: string;
  expiration_date?: string;
  payer_name?: string;
  payer_email?: string;
  checkout_url?: string;
  raw: ApiCharge | ApiSubscription;
}

// ─── Service ──────────────────────────────────────────────────────────────────

function buildQs(params?: Record<string, any>): string {
  if (!params) return '';
  const q = new URLSearchParams();
  Object.entries(params).forEach(([k, v]) => {
    if (v !== undefined && v !== null && v !== '') q.append(k, String(v));
  });
  const qs = q.toString();
  return qs ? `?${qs}` : '';
}

// ── One-time charges ──────────────────────────────────────────────────────────
export const chargesService = {
  list: async (params?: ChargesListParams): Promise<ChargesListResponse> => {
    // return fetchApi<ChargesListResponse>(`/charges${buildQs(params)}`);
    return Promise.resolve({
      charges: [
        { id: '1', token: 'tok_1', code: 'CHG-001', description: 'Consultoria Financeira', price: 500, status: 'PAID', expiration_date: new Date(Date.now() + 86400000*5).toISOString(), payer_name: 'Marcos Almeida', payer_email: 'marcos@example.com', checkout_url: 'https://checkout.tronnus.com/c/tok_1' },
        { id: '2', token: 'tok_2', code: 'CHG-002', description: 'E-book Guia Definitivo', price: 49.90, status: 'NOT_PAID', expiration_date: new Date(Date.now() + 86400000*2).toISOString(), payer_name: 'Juliana Costa', payer_email: 'juliana@example.com', checkout_url: 'https://checkout.tronnus.com/c/tok_2' },
        { id: '3', token: 'tok_3', code: 'CHG-003', description: 'Mentoria em Grupo', price: 1200, status: 'EXPIRED', expiration_date: new Date(Date.now() - 86400000*2).toISOString(), payer_name: 'Roberto Dias', payer_email: 'roberto@example.com', checkout_url: 'https://checkout.tronnus.com/c/tok_3' }
      ],
      meta: { current_page: 1, per_page: 10, total_count: 3 }
    });
  },

  get: async (token: string): Promise<ChargeDetailResponse> => {
    // return fetchApi<ChargeDetailResponse>(`/charges/${token}`);
    return Promise.resolve({
      charge: { id: '1', token, code: 'CHG-001', description: 'Mock Charge 1', price: 100, status: 'PAID', expiration_date: '10/10/2026', payer_name: 'John Doe', payer_email: 'john@example.com' }
    });
  },

  create: async (payload: CreateChargePayload): Promise<ChargeDetailResponse> => {
    // return fetchApi<ChargeDetailResponse>('/charges', { method: 'POST', body: JSON.stringify(payload) });
    return Promise.resolve({
      charge: { id: 'new', token: 'tok_new_mocked', code: 'CHG-NEW', description: payload.charge.description || 'Nova Cobrança', price: Number(payload.charge.products[0]?.price) || 100, status: 'NOT_PAID', expiration_date: payload.charge.expiration_date || '10/10/2026', payer_name: payload.charge.payer_name, payer_email: payload.charge.payer_email, checkout_url: '/checkout/tok_new_mocked' }
    });
  },

  processPayment: async (payload: ProcessPaymentPayload): Promise<any> => {
    // return fetchApi<any>('/payments', { method: 'POST', body: JSON.stringify(payload) });
    return Promise.resolve({ status: 'success', message: 'Payment processed successfully (Mock)' });
  },
};

// ── Plans ─────────────────────────────────────────────────────────────────────
export const plansService = {
  list: async (params?: { page?: number; per_page?: number }): Promise<PlansListResponse> => {
    // return fetchApi<PlansListResponse>(`/subscription/plans${buildQs(params)}`);
    return Promise.resolve({
      plans: [{ id: '1', token: 'plan_tok_1', name: 'Plano Básico', price: 50, periodicity: 1, public: true, status: 'active', created_at: new Date().toISOString() }],
      meta: { current_page: 1, per_page: 10, total_count: 1 }
    });
  },

  get: async (token: string): Promise<PlanDetailResponse> => {
    // return fetchApi<PlanDetailResponse>(`/subscription/plans/${token}`);
    return Promise.resolve({
      plan: { id: '1', token, name: 'Plano Básico', price: 50, periodicity: 1, public: true, status: 'active', created_at: new Date().toISOString() }
    });
  },

  create: async (payload: CreatePlanPayload): Promise<PlanDetailResponse> => {
    // return fetchApi<PlanDetailResponse>('/subscription/plans', { method: 'POST', body: JSON.stringify(payload) });
    return Promise.resolve({
      plan: { id: 'new_plan', token: 'new_plan_tok', name: payload.name, price: Number(payload.price), periodicity: payload.periodicity, public: payload.public || true, status: 'active', created_at: new Date().toISOString() }
    });
  },

  update: async (token: string, payload: Partial<CreatePlanPayload>): Promise<PlanDetailResponse> => {
    // return fetchApi<PlanDetailResponse>(`/subscription/plans/${token}`, { method: 'PUT', body: JSON.stringify(payload) });
    return Promise.resolve({
      plan: { id: '1', token, name: payload.name || 'Plano Básico', price: Number(payload.price || 50), periodicity: payload.periodicity || 1, public: payload.public !== false, status: 'active', created_at: new Date().toISOString() }
    });
  },
};

// ── Subscriptions ─────────────────────────────────────────────────────────────
export const subscriptionsService = {
  list: async (params?: { page?: number; per_page?: number }): Promise<SubscriptionsListResponse> => {
    // return fetchApi<SubscriptionsListResponse>(`/subscription/subscriptions${buildQs(params)}`);
    return Promise.resolve({
      subscriptions: [
        { id: 'sub_1', token: 'sub_tok_1', code: 'REC-001', status: 'active', customer: { id: 'cust_1', name: 'João Carlos', email: 'jc@example.com' }, expiration_day: 5, created_at: new Date(Date.now() - 86400000 * 30).toISOString(), next_billing_date: new Date(Date.now() + 86400000 * 5).toISOString(), plan: { id: 'plan_1', token: 'ptok', name: 'Plano Pro', price: 90, periodicity: 1, public: true, status: 'active' } },
        { id: 'sub_2', token: 'sub_tok_2', code: 'REC-002', status: 'active', customer: { id: 'cust_2', name: 'Maria Silva', email: 'maria@example.com' }, expiration_day: 15, created_at: new Date(Date.now() - 86400000 * 60).toISOString(), next_billing_date: new Date(Date.now() + 86400000 * 15).toISOString(), plan: { id: 'plan_1', token: 'ptok', name: 'Plano Pro', price: 90, periodicity: 1, public: true, status: 'active' } },
        { id: 'sub_3', token: 'sub_tok_3', code: 'REC-003', status: 'cancelled', customer: { id: 'cust_3', name: 'Pedro Alves', email: 'pedro@example.com' }, expiration_day: 10, created_at: new Date(Date.now() - 86400000 * 90).toISOString(), next_billing_date: new Date(Date.now() - 86400000 * 5).toISOString(), plan: { id: 'plan_1', token: 'ptok', name: 'Plano Básico', price: 50, periodicity: 1, public: true, status: 'active' } },
        { id: 'sub_4', token: 'sub_tok_4', code: 'REC-004', status: 'active', customer: { id: 'cust_4', name: 'Ana Souza', email: 'ana@example.com' }, expiration_day: 20, created_at: new Date(Date.now() - 86400000 * 15).toISOString(), next_billing_date: new Date(Date.now() + 86400000 * 20).toISOString(), plan: { id: 'plan_1', token: 'ptok', name: 'Plano Premium', price: 150, periodicity: 1, public: true, status: 'active' } }
      ],
      meta: { current_page: 1, per_page: 10, total_count: 4 }
    });
  },

  get: async (token: string): Promise<SubscriptionDetailResponse> => {
    // return fetchApi<SubscriptionDetailResponse>(`/subscription/subscriptions/${token}`);
    return Promise.resolve({
      subscription: { id: '1', token, status: 'active', customer: { id: 'cust_1', name: 'John Doe', email: 'john@example.com' }, expiration_day: 10, created_at: new Date().toISOString(), next_billing_date: new Date().toISOString() }
    });
  },

  create: async (payload: CreateSubscriptionPayload): Promise<SubscriptionDetailResponse> => {
    // return fetchApi<SubscriptionDetailResponse>('/subscription/subscriptions', { method: 'POST', body: JSON.stringify(payload) });
    return Promise.resolve({
      subscription: { id: 'new_sub', token: 'new_sub_tok', status: 'active', customer: { id: 'cust_new', name: payload.subscription.customer.name, email: payload.subscription.customer.email }, expiration_day: 1, created_at: new Date().toISOString(), next_billing_date: new Date().toISOString() }
    });
  },

  cancel: async (token: string): Promise<any> => {
    // return fetchApi<any>(`/subscription/subscriptions/cancel/${token}`, { method: 'PUT' });
    return Promise.resolve({ status: 'cancelled' });
  },

  /** POST /payments/full — first-time subscription payment with card */
  processFirstPayment: async (payload: ProcessSubscriptionPaymentPayload): Promise<any> => {
    // return fetchApi<any>('/payments/full', { method: 'POST', body: JSON.stringify(payload) });
    return Promise.resolve({ status: 'success', message: 'Subscription payment processed successfully (Mock)' });
  },
};

// ── Invoices ──────────────────────────────────────────────────────────────────
export const invoicesService = {
  list: async (params?: { page?: number; per_page?: number; status?: string }): Promise<InvoicesListResponse> => {
    // return fetchApi<InvoicesListResponse>(`/subscription/invoices${buildQs(params)}`);
    return Promise.resolve({
      invoices: [{ id: '1', token: 'inv_tok_1', status: 'paid', price: 50, created_at: new Date().toISOString() }],
      meta: { current_page: 1, per_page: 10, total_count: 1 }
    });
  },

  get: async (token: string): Promise<{ invoice: ApiInvoice }> => {
    // return fetchApi<{ invoice: ApiInvoice }>(`/subscription/invoices/${token}`);
    return Promise.resolve({
      invoice: { id: '1', token, status: 'paid', price: 50, created_at: new Date().toISOString() }
    });
  },

  /** POST /payments/pay — pay an existing invoice */
  pay: async (invoiceToken: string, customer: SubscriptionCustomer, payment: any): Promise<any> => {
    // return fetchApi<any>('/payments/pay', {
    //   method: 'POST',
    //   body: JSON.stringify({ order_type: 'invoice', token: invoiceToken, customer, payment }),
    // });
    return Promise.resolve({ status: 'success', message: 'Invoice paid successfully (Mock)' });
  },
};


// ─── Helper: periodicity number → human label ─────────────────────────────────
export const periodicityLabel: Record<number, string> = {
  1: 'Mensal',
  3: 'Trimestral',
  6: 'Semestral',
  12: 'Anual',
};

export const frequencyToPeriodicity: Record<string, number> = {
  mensal: 1,
  trimestral: 3,
  semestral: 6,
  anual: 12,
};
