import { fetchApi } from './client';
import { isMockSession, mockCharges, mockSubscriptions } from './mockData';

// ─── Shared ───────────────────────────────────────────────────────────────────

export interface ChargeProduct {
  name: string;
  price: string;       // API expects string e.g. "10.00"
  quantity: string;    // API expects string e.g. "1"
  description?: string;
}

// ─── One-Time Charges ─────────────────────────────────────────────────────────

export interface CreateChargePayload {
  charge: {
    payer_name?: string;
    payer_email?: string;
    expiration_date?: string; // "DD/MM/YYYY"
    code?: string;
    description?: string;
    products: ChargeProduct[];
  };
}

export interface ApiCharge {
  id: string;
  token: string;
  code: string;
  description: string;
  price: number;
  status: 'NOT_PAID' | 'PAID' | 'EXPIRED' | 'CANCELLED' | string;
  expiration_date: string;
  payer_name?: string;
  payer_email?: string;
  products?: ChargeProduct[];
  created_at?: string;
  updated_at?: string;
  checkout_url?: string;
  invoice_url?: string;
}

export interface ChargesListResponse {
  charges: ApiCharge[];
  meta: { current_page: number; per_page: number; total_count: number };
}

export interface ChargeDetailResponse {
  charge: ApiCharge;
}

export interface ChargesListParams {
  price?: number;
  status?: string;
  payer_name?: string;
  payer_email?: string;
  expiration_date_gt?: string;
  expiration_date_lt?: string;
  page?: number;
  per_page?: number;
}

// ─── Subscription Plans ───────────────────────────────────────────────────────

export interface CreatePlanPayload {
  name: string;
  description?: string;
  code?: string;
  price: string; // "10.00"
  /** Periodicity in months: 1=monthly, 3=quarterly, 6=semiannual, 12=annual */
  periodicity: number;
  public?: boolean;
}

export interface ApiPlan {
  id: string;
  token: string;
  name: string;
  description?: string;
  code?: string;
  price: number;
  periodicity: number;
  public: boolean;
  status: string;
  created_at?: string;
}

export interface PlansListResponse {
  plans: ApiPlan[];
  meta: { current_page: number; per_page: number; total_count: number };
}

export interface PlanDetailResponse {
  plan: ApiPlan;
}

// ─── Subscriptions ────────────────────────────────────────────────────────────

export interface SubscriptionCustomer {
  id?: string;
  name: string;
  email: string;
  document: string;
  phone?: string;
}

export interface CreateSubscriptionPayload {
  subscription: {
    customer: SubscriptionCustomer;
    code?: string;
    plans: { id: string; price?: number }[];
    items?: { description: string; price: number }[];
  };
}

export interface ApiSubscription {
  id: string;
  token: string;
  code?: string;
  status: 'active' | 'cancelled' | 'suspended' | string;
  customer: { id: string; name: string; email: string };
  plan?: ApiPlan;
  plans?: ApiPlan[];
  expiration_day?: number;
  created_at?: string;
  next_billing_date?: string;
}

export interface SubscriptionsListResponse {
  subscriptions: ApiSubscription[];
  meta: { current_page: number; per_page: number; total_count: number };
}

export interface SubscriptionDetailResponse {
  subscription: ApiSubscription;
}

// ─── Invoices (auto-generated by subscriptions) ───────────────────────────────

export interface ApiInvoice {
  id: string;
  token: string;
  status: 'waiting_payment' | 'paid' | 'expired' | string;
  price: number;
  expiration_date?: string;
  starts_at?: string;
  ends_at?: string;
  subscription?: { token: string; code?: string };
  created_at?: string;
}

export interface InvoicesListResponse {
  invoices: ApiInvoice[];
  meta: { current_page: number; per_page: number; total_count: number };
}

// ─── Payment / Checkout ───────────────────────────────────────────────────────

export interface ProcessPaymentPayload {
  token: string;
  payment_method: 'credit_card' | 'pix';
  card_number?: string;
  card_holder_name?: string;
  card_expiration_date?: string;
  card_cvv?: string;
  installments?: number;
  customer_name: string;
  customer_email: string;
  customer_document: string;
  customer_phone: string;
}

export interface ProcessSubscriptionPaymentPayload {
  /** plan token */
  plan_token: string;
  customer: SubscriptionCustomer;
  payment: {
    method: 'credit_card' | 'pix';
    recurrency: true;
    card_number?: string;
    card_holder_name?: string;
    card_expiration_date?: string;
    card_cvv?: string;
    installments?: number;
  };
}

// ─── Unified "charge" shape used in UI ───────────────────────────────────────

export type ChargeType = 'one_time' | 'subscription';

export interface UnifiedCharge {
  type: ChargeType;
  token: string;
  code?: string;
  description: string;
  price: number;
  status: string;
  expiration_date?: string;
  payer_name?: string;
  payer_email?: string;
  checkout_url?: string;
  raw: ApiCharge | ApiSubscription;
}

// ─── Service ──────────────────────────────────────────────────────────────────

function buildQs(params?: Record<string, any>): string {
  if (!params) return '';
  const q = new URLSearchParams();
  Object.entries(params).forEach(([k, v]) => {
    if (v !== undefined && v !== null && v !== '') q.append(k, String(v));
  });
  const qs = q.toString();
  return qs ? `?${qs}` : '';
}

// ── One-time charges ──────────────────────────────────────────────────────────
export const chargesService = {
  list: async (params?: ChargesListParams): Promise<ChargesListResponse> => {
    try {
      return await fetchApi<ChargesListResponse>(`/charges${buildQs(params)}`);
    } catch (error) {
      if (isMockSession()) {
        return {
          charges: mockCharges as any,
          meta: { current_page: 1, per_page: 50, total_count: mockCharges.length }
        };
      }
      throw error;
    }
  },

  get: async (token: string): Promise<ChargeDetailResponse> => {
    try {
      return await fetchApi<ChargeDetailResponse>(`/charges/${token}`);
    } catch (error) {
      if (isMockSession()) {
        const charge = mockCharges.find(c => c.token === token);
        return { charge: charge as any };
      }
      throw error;
    }
  },

  create: async (payload: CreateChargePayload): Promise<ChargeDetailResponse> => {
    try {
      return await fetchApi<ChargeDetailResponse>('/charges', { method: 'POST', body: JSON.stringify(payload) });
    } catch (error) {
      if (isMockSession()) {
        const newCharge = {
          token: 'mock_' + Date.now(),
          code: 'MOCK' + Math.floor(Math.random() * 1000),
          description: payload.charge.description,
          price: payload.charge.products.reduce((a, b) => a + parseFloat(b.price) * parseInt(b.quantity), 0),
          status: 'NOT_PAID',
          expiration_date: payload.charge.expiration_date || '—',
        };
        return { charge: newCharge as any };
      }
      throw error;
    }
  },

  processPayment: (payload: ProcessPaymentPayload): Promise<any> =>
    fetchApi<any>('/payments', { method: 'POST', body: JSON.stringify(payload) }),
};

// ── Plans ─────────────────────────────────────────────────────────────────────
export const plansService = {
  list: async (params?: { page?: number; per_page?: number }): Promise<PlansListResponse> => {
    try {
      return await fetchApi<PlansListResponse>(`/subscription/plans${buildQs(params)}`);
    } catch (error) {
      if (isMockSession()) {
        return {
          plans: [],
          meta: { current_page: 1, per_page: 50, total_count: 0 }
        };
      }
      throw error;
    }
  },

  get: async (token: string): Promise<PlanDetailResponse> => {
    try {
      return await fetchApi<PlanDetailResponse>(`/subscription/plans/${token}`);
    } catch (error) {
      if (isMockSession()) {
        throw new Error('Plano não encontrado (MOCK)');
      }
      throw error;
    }
  },

  create: async (payload: CreatePlanPayload): Promise<PlanDetailResponse> => {
    try {
      return await fetchApi<PlanDetailResponse>('/subscription/plans', { method: 'POST', body: JSON.stringify(payload) });
    } catch (error) {
      if (isMockSession()) {
        return {
          plan: {
            id: 'mock_plan',
            token: 'mock_plan_' + Date.now(),
            name: payload.name,
            price: parseFloat(payload.price),
            periodicity: payload.periodicity,
            public: true,
            status: 'active'
          } as any
        };
      }
      throw error;
    }
  },

  update: (token: string, payload: Partial<CreatePlanPayload>): Promise<PlanDetailResponse> =>
    fetchApi<PlanDetailResponse>(`/subscription/plans/${token}`, { method: 'PUT', body: JSON.stringify(payload) }),
};

// ── Subscriptions ─────────────────────────────────────────────────────────────
export const subscriptionsService = {
  list: async (params?: { page?: number; per_page?: number }): Promise<SubscriptionsListResponse> => {
    try {
      return await fetchApi<SubscriptionsListResponse>(`/subscription/subscriptions${buildQs(params)}`);
    } catch (error) {
      if (isMockSession()) {
        return {
          subscriptions: mockSubscriptions as any,
          meta: { current_page: 1, per_page: 50, total_count: mockSubscriptions.length }
        };
      }
      throw error;
    }
  },

  get: async (token: string): Promise<SubscriptionDetailResponse> => {
    try {
      return await fetchApi<SubscriptionDetailResponse>(`/subscription/subscriptions/${token}`);
    } catch (error) {
      if (isMockSession()) {
        const sub = mockSubscriptions.find(s => s.token === token);
        return { subscription: sub as any };
      }
      throw error;
    }
  },

  create: async (payload: CreateSubscriptionPayload): Promise<SubscriptionDetailResponse> => {
    try {
      return await fetchApi<SubscriptionDetailResponse>('/subscription/subscriptions', { method: 'POST', body: JSON.stringify(payload) });
    } catch (error) {
      if (isMockSession()) {
        return {
          subscription: {
            id: 'mock_sub',
            token: 'mock_sub_' + Date.now(),
            status: 'active',
            customer: payload.subscription.customer,
            created_at: new Date().toISOString()
          } as any
        };
      }
      throw error;
    }
  },

  cancel: async (token: string): Promise<any> => {
    try {
      return await fetchApi<any>(`/subscription/subscriptions/cancel/${token}`, { method: 'PUT' });
    } catch (error) {
      if (isMockSession()) return { success: true };
      throw error;
    }
  },

  /** POST /payments/full — first-time subscription payment with card */
  processFirstPayment: async (payload: ProcessSubscriptionPaymentPayload): Promise<any> => {
    try {
      return await fetchApi<any>('/payments/full', { method: 'POST', body: JSON.stringify(payload) });
    } catch (error) {
      if (isMockSession()) return { success: true, token: 'mock_pay_token' };
      throw error;
    }
  },
};

// ── Invoices ──────────────────────────────────────────────────────────────────
export const invoicesService = {
  list: async (params?: { page?: number; per_page?: number; status?: string }): Promise<InvoicesListResponse> => {
    try {
      return await fetchApi<InvoicesListResponse>(`/subscription/invoices${buildQs(params)}`);
    } catch (error) {
      if (isMockSession()) {
        return {
          invoices: [],
          meta: { current_page: 1, per_page: 50, total_count: 0 }
        };
      }
      throw error;
    }
  },

  get: async (token: string): Promise<{ invoice: ApiInvoice }> => {
    try {
      return await fetchApi<{ invoice: ApiInvoice }>(`/subscription/invoices/${token}`);
    } catch (error) {
      if (isMockSession()) {
        return {
          invoice: { id: 'mock_inv', token, status: 'paid', price: 100 } as any
        };
      }
      throw error;
    }
  },

  /** POST /payments/pay — pay an existing invoice */
  pay: async (invoiceToken: string, customer: SubscriptionCustomer, payment: any): Promise<any> => {
    try {
      return await fetchApi<any>('/payments/pay', {
        method: 'POST',
        body: JSON.stringify({ order_type: 'invoice', token: invoiceToken, customer, payment }),
      });
    } catch (error) {
      if (isMockSession()) return { success: true };
      throw error;
    }
  },
};


// ─── Helper: periodicity number → human label ─────────────────────────────────
export const periodicityLabel: Record<number, string> = {
  1: 'Mensal',
  3: 'Trimestral',
  6: 'Semestral',
  12: 'Anual',
};

export const frequencyToPeriodicity: Record<string, number> = {
  mensal: 1,
  trimestral: 3,
  semestral: 6,
  anual: 12,
};
